# See https://github.com/contently/infra/blob/master/docs/infra.yaml.md for information about the structure and purpose of this file.
environment_variables:
  - APP_NAME: amanda-api
applications:
  - name: "{{ context.ENVIRONMENT_SETTINGS.APP_NAME }}"
    dockerfile: Dockerfile
    kubernetes_app:
      name: "{{ context.ENVIRONMENT_SETTINGS.APP_NAME }}"
      image_locations:
        - kind: Deployment
          name: amanda-api
          jsonpaths:
            - "$.spec.template.spec.containers[?name='amanda-api'].image"
